package csst15

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {


        all(uri: "/**") {
            before = {

                // Ignore direct views (e.g. the default main index page).
                if (webRequest.controllerName == "user" && webRequest.actionName == "profile") {
//                    accessControl()
                } else {
                    return true;
                }
            }
        }

    }
}
